import {MRT_Localization} from "material-react-table";

export const MrGridLocalizationRu:MRT_Localization = {
    actions: 'Действия',
    cancel: 'Отмена',
    changeFilterMode: 'Изменить режим фильтрации',
    changeSearchMode: 'Изменить режим поиска',
    clearFilter: 'Очистить фильтр',
    clearSearch: 'Очистить поиск',
    clearSort: 'Убрать сортирвку',
    collapse: 'Свернуть',
    collapseAll: 'Свернуть все',
    columnActions: 'Действия со столбцом',
    edit: 'Релактирование',
    expand: 'Развернуть',
    expandAll: 'Развернуть все',
    filterByColumn: 'Фильтр по столбцу {column}',
    groupByColumn: 'Группировка по столбцу {column}',
    groupedBy: 'Группировка по ',
    hideAll: 'Скрыть все',
    hideColumn: 'Скрыть столбец {column}',
    move:'Переместить',
    noRecordsToDisplay: 'Нет данных для отображения',
    noResultsFound: 'Ничего не найдено',
    resetColumnSize: 'Сбросить размер столбцов',
    resetOrder: 'Сбросить порядок',
    rowActions: 'Действия со строками',
    save: 'Сохранить',
    search: 'Поиск',
    selectedCountOfRowCountRowsSelected: 'Выбрано {selectedCount} из {rowCount} строк(а)',
    showAll: 'Показать все',
    showHideColumns: 'Показать/скрыть столбцы',
    showHideFilters: 'Включить/отключить фильтр',
    showHideSearch: 'Включить/отключить поиск',
    sortByColumnAsc: 'Сортировать столбец {column} по возрастанию',
    sortByColumnDesc: 'Сортировать стобец {column} по убыванию',
    sortedByColumnAsc: 'Отсортировано по возрастанию',
    sortedByColumnDesc: 'Отсортировано по убыванию',
    thenBy: ', затем по ',
    toggleDensity: 'Переключить плотность',
    toggleFullScreen: 'Включить полноэкранный режим',
    toggleSelectAll: 'Выбрать все',
    toggleSelectRow: 'Выбрать строку',
    ungroupByColumn: 'Разгруппировать по {column}',
    unsorted: 'Без сортировки',
};
